defaults:
  - default

strategy: ddp

accelerator: gpu
devices: "auto"
num_nodes: 1
sync_batchnorm: true

plugins:
  - _target_: lightning.pytorch.plugins.environments.SLURMEnvironment
    auto_requeue: false
