defaults:
  - default
  - net: tarflow
  - scheduler: cosine

_target_: src.models.normalizing_flow_module.NormalizingFlowLitModule

prior:
  _target_: src.models.priors.normal_distribution.NormalDistribution
  num_dimensions: ${data.num_dimensions}
  mean: 0.0
  std: 1.0
  mean_free: false

optimizer:
  lr: 1e-4
  betas:
    - 0.9
    - 0.95
  weight_decay: 4e-4
ema_decay: 0.999