defaults:
  - model_summary
  - lr_monitor
  - model_checkpoint_resampled_energy_w2
  - model_checkpoint_time
  - model_checkpoint_loss
  - sampling_evaluation
  - _self_

model_summary:
  max_depth: 2
