sampling_evaluation:
  _target_: src.callbacks.sampling_evaluation.SamplingEvaluationCallback
  run_on_validation_epoch_end: true
  run_on_test_epoch_end: true
  evaluator:
    _target_: src.evaluation.evaluator.Evaluator
    fix_symmetry: true
    drop_unfixable_symmetry: false
    num_eval_samples: 10_000
