# @package _global_

# uses only 1% of the training data and 5% of validation/test data

defaults:
  - default

trainer:
  max_epochs: 2
  limit_train_batches: 2
  limit_val_batches: 2
  limit_test_batches: 2
  accelerator: gpu
